# Generated by Django 5.2.7 on 2025-10-13 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('idDispositivo', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('calleynumero', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('idEnfermedad', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipoUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('idLectura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('PM2_5', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('luz', models.IntegerField()),
                ('CO2', models.IntegerField()),
                ('presion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dispositivo', models.ForeignKey(db_column='idDispositivo', on_delete=django.db.models.deletion.CASCADE, to='core.dispositivo')),
            ],
            options={
                'db_table': 'lecturas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('aPaterno', models.CharField(max_length=45)),
                ('aMaterno', models.CharField(max_length=45)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('atleta', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('enfermedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enfermedad')),
                ('tipoUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipousuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
