# Generated by Django 5.2.7 on 2025-12-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipousuario',
            old_name='tipoUsuario',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='tipo',
            new_name='nombre_tipo',
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='tipousuario',
        ),
    ]
