# Generated by Django 5.2.7 on 2026-06-02 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_dispositivos_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('municipio', models.CharField(max_length=64)),
                ('estado', models.CharField(max_length=64)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('universidad', 'Universidad')], max_length=20)),
                ('clave_centro_trabajo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'escuelas',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='core.escuela'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.escuela'),
        ),
    ]
