"""
Django settings for CityAirLog project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # <-- Añadido para unirse a las rutas

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-509bq=ym+_-%4tz-(9_9w5p+hwa*1mv^qm7378)0n*u0$h%x#5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CityAirLog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # <--- **MODIFICADO**
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CityAirLog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# --- ¡CONFIGURACIÓN DE STATIC CORREGIDA! ---
# Le decimos a Django que busque archivos estáticos en la carpeta 'core/static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static'),
]
# (Opcional, pero buena práctica para producción)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# --- FIN DE LA CORRECCIÓN ---


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CONFIGURACIÓN DE RUTAS PARA EL MODELO DE ML ---
# (Asegúrate de que BASE_DIR esté definido arriba, Django ya lo hace)

# 1. Carpeta donde el script buscará los DATOS DE ENTRADA (CSV/XLSX)
# (Debes crear una carpeta 'data_input' en la raíz de tu proyecto)
INPUT_DIR_BASE = BASE_DIR / 'data_input' 

# 2. Carpeta donde el script guardará los RESULTADOS (TXT, CSV, PNG)
# (Debes crear una carpeta 'data_output' en la raíz de tu proyecto)
OUT_DIR = BASE_DIR / 'data_output'

# 3. Ruta completa al archivo CSV de predicciones que la vista 'resumen' leerá
# (Asegúrate de que coincida con el nombre en run_model.py)
RUTA_DATOS_MODELO = OUT_DIR / 'predicciones_PM2_5.csv'