"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# BASE_DIR ya debe estar definido así:
BASE_DIR = Path(__file__).resolve().parent.parent

# ...

# Archivos estáticos (CSS, JS, imágenes)
STATIC_URL = '/static/'

# Esta línea da el error porque BASE_DIR no estaba definido
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5rx&4)3@c7c&8cj=s6jo$@m@bc5&7cnc8n&#44(-03e6j!rao$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',        # <- NUEVO
    'rest_framework',   # <- NUEVO (si vas a exponer API)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / 'templates'],  # opcional si usas carpeta global
        'APP_DIRS': True,                    # IMPORTANTE
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'air_quality.wsgi.application'
# (si existe)
ASGI_APPLICATION = 'air_quality.asgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ====================================================================
# CONFIGURACIÓN DE RUTAS PORTABLES (AÑADIR AL FINAL DEL ARCHIVO)
# ====================================================================

# RUTA DATOS PORTABLE:
# La lógica: BASE_DIR ('Dashboard/') + '..' (sube a 'CodigosResidencia/') 
# y luego entra a 'salidas_modelo/'

# Carpeta base para la BÚSQUEDA de los datos de ENTRADA. 
# Apunta a la carpeta superior ('CodigosResidencia') donde está el CSV/XLSX original.
INPUT_DIR_BASE = os.path.join(BASE_DIR, '..')

# Carpeta de SALIDA (donde se guardan el CSV y el PNG). 
# Apunta a 'CodigosResidencia/salidas_modelo'.
OUT_DIR = os.path.join(BASE_DIR, '..', 'salidas_modelo')

# RUTA DATOS DE SALIDA (CSV) que usa la vista 'resumen'.
# Esto es: [CodigosResidencia]/salidas_modelo/predicciones_PM2_5.csv
# Esta variable es usada por views.py

RUTA_DATOS_MODELO = os.path.join(
    BASE_DIR, 
    '..', 
    'salidas_modelo', 
    'predicciones_PM2_5.csv'
)
